#kubectl apply -f deployment.yaml
# all the yaml file start from top to bottom and left to right
#we know that kubectl interact with kubernets using an api
apiVersion: apps/v1 #this will invoke the apps/v1 api
kind: Deployment #which api Deployment api it will invoke
metadata:
  name: usermgmt-webapp #and create and deployment with this name
  labels: 
    app: usermgmt-webapp
spec:
  replicas: 1 #replicacount as 3 inside this deployment it will create three pod
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:
    metadata:
      labels:
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME 
              value: "webappdb"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-sql-db-password
                  key: db-password
          ports:
            - containerPort: 3306 #this will be expose internally inside your k8s cluster
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql #inside your container the path where your mysql data is stored  
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
        - name: usermanagement-dbcreation-script
          configMap:
              name: usermanagement-dbcreation-script
